### ISSUE TITLE
query conditions should be modified

### ISSUE THREAD

**Issue by alireza-saberi** [armin-es/HTML-and-CSS-Test#1]
Media queries need ``screen only` condition. Also put `max-width: 999px` and with `min-width: 500px`
`@media screen only and (min-width:500px and max-width: 999px){}`

You can also put the media query inside a new file by using the following trick:
`<link rel="stylesheet" media="(max-width: 800px)" href="example.css" />`

**Comment by armin-es** [comment]
- `only screen` condition added to media queries.
- Shorthand properties used for `margin` and `font`
- `max-width` condition added
